### ISSUE TITLE
Download column audio

### ISSUE THREAD

**Issue by nicoxiang** [nicoxiang/geektime-downloader#1]
We will see if this feature is essential

**Comment by nicoxiang** [comment]
#5

**Comment by ZLGG** [comment]
能加上，文章上面的语音吗

**Comment by nicoxiang** [comment]
> 能加上，文章上面的语音吗

感谢建议，这个功能正在收集建议阶段，如果需要的人比较多，后面会考虑加上

**Comment by Scal-VictorLi** [comment]
同希望加上语音，现在合体使用https://github.com/jachinlin/geektime_dl下音频

**Comment by nicoxiang** [comment]
@Scal-VictorLi  @ZLGG v0.7.1 版本已支持下载音频功能
