### ISSUE TITLE
专栏包含的视频无法下载吗？

### ISSUE THREAD

**Issue by cloud-arrow** [nicoxiang/geektime-downloader#104]
你好的专栏包含的视频无法下载吗？比如这个专栏 [https://time.geekbang.org/column/intro/100028301](https://time.geekbang.org/column/intro/100028301)

都没有video的目录

<img width="576" alt="截屏2023-04-02 22 15 42" src="https://user-images.githubusercontent.com/52516729/229358495-a0dff4e2-d734-4ed4-8c27-f9bf732e5cf5.png">

@nicoxiang 大佬求解答

**Comment by nicoxiang** [comment]
能否麻烦提供下包含视频的章节文章名称



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: king ***@***.***&gt;
发送时间: 2023年4月2日 22:20
收件人: nicoxiang/geektime-downloader ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [nicoxiang/geektime-downloader] 专栏包含的视频无法下载吗？ (Issue #104)





 
你好的专栏包含的视频无法下载吗？比如这个专栏 https://time.geekbang.org/column/intro/100028301
 
都没有video的目录

**Comment by cloud-arrow** [comment]
章节名称是：13 | [视频]实战：基于FFI实现的lua-resty-lrucache @nicoxiang

**Comment by nicoxiang** [comment]
这种类型的文章第一次见，之前遇到过如课程《Kubernetes 入门实战课》是文字型文章中内嵌了多个视频，而这个又不太一样，这个是整个章节都是一个视频，接口返回上有所不同，下个版本会一起支持

**Comment by nicoxiang** [comment]
新的v0.10.2版本已支持此类型文章视频

**Comment by cloud-arrow** [comment]
> 新的v0.10.2版本已支持此类型文章视频

使用新版本的会出现这个问题
An error occurred: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""

<img width="1782" alt="截屏2023-04-06 12 43 19" src="https://user-images.githubusercontent.com/52516729/230273883-94e46e53-17ca-471e-9b62-53569d3e745b.png">
