### ISSUE TITLE
下载出错

### ISSUE THREAD

**Issue by cloud-arrow** [nicoxiang/geektime-downloader#105]
使用0.9.2的版本下载软件工程之美出错，课程地址是https://time.geekbang.org/column/intro/100023701

报错信息如下

已完成下载41/55An error occurred: parse "https!%5B://static001.g%5D(https://static001.geekbang.org/resource/image/78/9c/788180c8c6dd9b69b2784d2a780a239c.jpg": first path segment in URL cannot contain colon

**Comment by nicoxiang** [comment]
能否麻烦提供下章节文章名称和下载类型(pdf还是markdown)



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: king ***@***.***&gt;
发送时间: 2023年4月4日 12:54
收件人: nicoxiang/geektime-downloader ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [nicoxiang/geektime-downloader] 下载出错 (Issue #105)





 
使用0.9.2的版本下载软件工程之美出错，课程地址是https://time.geekbang.org/column/intro/100023701
 
报错信息如下
 
已完成下载41/55An error occurred: parse "https!%5B://static001.g%5D(https://static001.geekbang.org/resource/image/78/9c/788180c8c6dd9b69b2784d2a780a239c.jpg": first path segment in URL cannot contain colon

**Comment by nicoxiang** [comment]
看了下，文章末尾有一块错误的图片地址（就是报错中的地址），地址中半截是就是顶部的图片地址，应该是作者维护的时候复制错了。最后导致我这边把他当作图片下载，但这个不是一个正确的图片地址。

<img width="517" alt="image" src="https://user-images.githubusercontent.com/11958087/230091995-9c6544d1-6be1-4497-9860-a76dc17ff931.png">

**Comment by nicoxiang** [comment]
这个我这边没法处理的，因为原文中图片的路径就是坏死的，如果你想下载后面的几篇文章，可能需要你这边手动选择文章，并逐篇下载了。后面版本我做下改动，下载失败的图片我就跳过了。
