### ISSUE TITLE
感谢作者提供的工具，现在有一个markdown格式下载不完整的问题

### ISSUE THREAD

**Issue by sum86** [nicoxiang/geektime-downloader#113]
使用--output 7 输出后，仅有部分文章有markdown格式，很多都只能导出PDF格式。用--output 6也是一样的结果。音频没有确实，就是markdown 缺失。 @nicoxiang

**Comment by nicoxiang** [comment]
缺失的课程的名称/id和章节名称/id 可以发一下吗？我看下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sum86 ***@***.***&gt;
发送时间: 2023年5月30日 14:54
收件人: nicoxiang/geektime-downloader ***@***.***&gt;
抄送: Nico Xiang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [nicoxiang/geektime-downloader] 感谢作者提供的工具，现在有一个markdown格式下载不完整的问题 (Issue #113)





 
使用--output 7 输出后，仅有部分文章有markdown格式，很多都只能导出PDF格式。用--output 6也是一样的结果。音频没有确实，就是markdown 缺失。 @nicoxiang

**Comment by sum86** [comment]
![image](https://github.com/nicoxiang/geektime-downloader/assets/14838827/187e0350-d0a6-447b-857f-e8337e8fa89d)
比如TonyBai·Go语言第一课 整个课程仅有这些MD输出，其他的章节都没有。如果用output6也是一样的情况。

**Comment by hfy0** [comment]
课程ID：100541001，导出markdown格式失败
![image](https://github.com/nicoxiang/geektime-downloader/assets/74233307/9de8740c-0bea-4e59-aeec-55a16e004b42)

**Comment by nicoxiang** [comment]
已在 v0.10.4 版本修复 markdown 下载 bug
