### ISSUE TITLE
不能用cookie下载吗

### ISSUE THREAD

**Issue by chemson** [nicoxiang/geektime-downloader#12]

**Comment by nicoxiang** [comment]
@chemson  暂时没支持这个功能，现在完成登录就是保存 cookie 到本地，没想到用 cookie 登录的优点，反而是要去网页 cookie 里找到复制

**Comment by chemson** [comment]
加入企业微信可以使用免费会员一个月，只能用cookie下载hhh

**Comment by nicoxiang** [comment]
@chemson 原来是这样，我明天看下，如果好加的话可以加下这个功能

**Comment by chemson** [comment]
谢谢大佬

**Comment by nicoxiang** [comment]
@chemson Try the new feature in release 0.2.4. Thanks for your suggestion.

**Comment by nicoxiang** [comment]
@chemson Any questions on this?
