### ISSUE TITLE
0.10.5报错

### ISSUE THREAD

**Issue by freecow** [nicoxiang/geektime-downloader#123]
如题，采用0.10.5版本，下载训练营课程的时候报错：
An error occurred: json: cannot unmarshal array into Go struct field V1ArticleResponse.data of type struct { ArticleContent string "json:\"article_content\""; ArticleTitle string "json:\"article_title\""; InlineVideoSubtitles []struct { VideoURL string "json:\"video_url\""; VideoFreeURL string "json:\"video_free_url\""; VideoVid string "json:\"video_vid\""; VideoSubtitle string "json:\"video_subtitle\""; VideoFreeVid string "json:\"video_free_vid\""; VideoFreeSubtitle string "json:\"video_free_subtitle\"" } "json:\"inline_video_subtitles\""; AudioDownloadURL string "json:\"audio_download_url\"" }

**Comment by nicoxiang** [comment]
是哪门课呢？课程是视频的形式吗？目前只支持下载训练营中的视频

**Comment by freecow** [comment]
是训练营，ID是522

**Comment by nicoxiang** [comment]
训练营名称是什么呢？课程里面是不是没有视频啊？

**Comment by nicoxiang** [comment]
@freecow 
不好意思，我这边手头没有这个训练营，打不开训练营详情，也不知道训练营名称，也没法 debug，现在只能猜测这个训练营里没有视频，因为目前只支持下载训练营中的视频

**Comment by nicoxiang** [comment]
可以试试 [0.10.6-beta](https://github.com/nicoxiang/geektime-downloader/releases/tag/v0.10.6) 这个版本
