### ISSUE TITLE
《AI 绘画核心技术与实战》这门课下载一直超时，有没有人跟我一样？

### ISSUE THREAD

**Issue by hjijin** [nicoxiang/geektime-downloader#127]
下载不了《[AI 绘画核心技术与实战](https://time.geekbang.org/column/intro/100555001?tab=catalog)》

**Comment by nicoxiang** [comment]
关闭vpn下载，如果还有问题，麻烦把报错信息贴下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HuangJiJin ***@***.***&gt;
发送时间: 2023年8月5日 13:07
收件人: nicoxiang/geektime-downloader ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [nicoxiang/geektime-downloader] 《AI 绘画核心技术与实战》这门课下载一直超时，有没有人跟我一样？ (Issue #127)





 
下载不了《AI 绘画核心技术与实战》

**Comment by nicoxiang** [comment]
能否贴下 %AppData%\geektime-downloader\geektime-downloader.log 中的内容，只看截图看不出来是哪个接口超时了

**Comment by nicoxiang** [comment]
已在0.11.1版本修复
