### ISSUE TITLE
训练营反序列化错误

### ISSUE THREAD

**Issue by Bank5y** [nicoxiang/geektime-downloader#130]
报错代码
An error occurred: json: cannot unmarshal array into Go struct field V1ArticleResponse.data of type struct { ArticleContent string "json:\"article_content\""; ArticleTitle string "json:\"article_title\""; InlineVideoSubtitles []struct { VideoURL string "json:\"video_url\""; VideoFreeURL string "json:\"video_free_url\""; VideoVid string "json:\"video_vid\""; VideoSubtitle string "json:\"video_subtitle\""; VideoFreeVid string "json:\"video_free_vid\""; VideoFreeSubtitle string "json:\"video_free_subtitle\"" } "json:\"inline_video_subtitles\""; AudioDownloadURL string "json:\"audio_download_url\"" }

**Comment by nicoxiang** [comment]
可以试试 [0.10.6-beta](https://github.com/nicoxiang/geektime-downloader/releases/tag/v0.10.6) 这个版本
