### ISSUE TITLE
训练营下载，有下载不完的情况，很多视频下载到98% 99%就断了

### ISSUE THREAD

**Issue by blueskyzs** [nicoxiang/geektime-downloader#137]
![微信图片_20230829222547](https://github.com/nicoxiang/geektime-downloader/assets/6936254/4bf705f9-5784-4700-88f6-092d72a34c11)

**Comment by nicoxiang** [comment]
先看看目标文件夹有没有生成下载好的文件，有可能是进度条显示问题。等我有空了看下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: blueskyzs ***@***.***&gt;
发送时间: 2023年8月29日 22:26
收件人: nicoxiang/geektime-downloader ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [nicoxiang/geektime-downloader] 训练营下载，有下载不完的情况，很多视频下载到98% 99%就断了 (Issue #137)
