### ISSUE TITLE
windows11 怎么主动清除登录信息，退出登录？

### ISSUE THREAD

**Issue by chenlixin93** [nicoxiang/geektime-downloader#138]
最近改过账户密码，之前还能下载的。但是最新提示：ResponseBody: {"code":-1,"data":{},"error":{"code":-3000,"msg":"用户没有大学权限"}

**Comment by nicoxiang** [comment]
如果是windows 在 %AppData%/geektime-downloader 目录下，把你的用户目录删掉就可以了
