### ISSUE TITLE
Mac 上无法使用

### ISSUE THREAD

**Issue by strivecheng** [nicoxiang/geektime-downloader#139]
大佬，我是 Mac，通过 go 下载的不行，下载darwin也不行，运行直接报错
<img width="547" alt="image" src="https://github.com/nicoxiang/geektime-downloader/assets/20623884/cc74d0fb-bfa7-4cea-8b3b-eb1e7ae4fe4f">
geektime-downloader 命令也无法使用

**Comment by nicoxiang** [comment]
要传参数的，你看下readme



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: strivecheng ***@***.***&gt;
发送时间: 2023年9月8日 23:19
收件人: nicoxiang/geektime-downloader ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [nicoxiang/geektime-downloader] Mac 上无法使用 (Issue #139)





 
大佬，我是 Mac，通过 go 下载的不行，下载darwin也不行，运行直接报错
 
 geektime-downloader 命令也无法使用

**Comment by strivecheng** [comment]
> 要传参数的，你看下readme 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: strivecheng ***@***.***&gt; 发送时间: 2023年9月8日 23:19 收件人: nicoxiang/geektime-downloader ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [nicoxiang/geektime-downloader] Mac 上无法使用 (Issue #139) 大佬，我是 Mac，通过 go 下载的不行，下载darwin也不行，运行直接报错 geektime-downloader 命令也无法使用 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
