### ISSUE TITLE
下载中途报错：尚未购买该课程

### ISSUE THREAD

**Issue by lonelystone545** [nicoxiang/geektime-downloader#150]
在下载课程时发现，下载到一部分后报错：尚未购买该课程。退出重新登录后输入课程ID依然报错，但是直接通过网页登录是可以的

**Comment by lonelystone545** [comment]
![image](https://github.com/nicoxiang/geektime-downloader/assets/20380902/64e3eac5-3aeb-44da-a7af-89323c6a9c8c)

**Comment by lonelystone545** [comment]
账号好像废掉了，输入任何课程都提示未购买。是被服务端针对账号或者设置做了限制么？

**Comment by nicoxiang** [comment]
你是不是会员？不是单独买的这个课？先在客户端里看一下这个课程，把这个课加到你的课程列表里面

**Comment by lonelystone545** [comment]
是会员，已经把这个课程加入到课程列表中了，如下图：
![image](https://github.com/nicoxiang/geektime-downloader/assets/20380902/898361f2-11cf-4e9b-a509-aeb0544385ba)

从现象来看，是被服务端拉黑了，现在所有的课程无法通过命令来下载了，但是在网页和客户端是可以正常的访问。。😭

**Comment by nicoxiang** [comment]
加入到课程列表以后还是返回 “用户未购买此专栏“ 吗？没有拉黑什么的，最多也就是限流，别担心

**Comment by lonelystone545** [comment]
那现在就无法使用了嘛？或者后续有没有规避的办法

**Comment by Mercy1101** [comment]
> 是会员，已经把这个课程加入到课程列表中了，如下图： ![image](https://private-user-images.githubusercontent.com/20380902/277907442-898361f2-11cf-4e9b-a509-aeb0544385ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzg2OTgsIm5iZiI6MTcwMjEzODM5OCwicGF0aCI6Ii8yMDM4MDkwMi8yNzc5MDc0NDItODk4MzYxZjItMTFjZi00ZTliLWE1MDktYWViMDU0NDM4NWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE2MTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOGY3M2MwNzM2YWExY2JiNDhiMThiZDgxYjVhNjk0ODFkMTE4MjUwMGI3ZDI4MDI2OGIwNDNmMzM2MzBmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QbyGVLDiXPSMMLSnjng8aNtkoFdP6o3QKglrNvM0hg0)
> 
> 从现象来看，是被服务端拉黑了，现在所有的课程无法通过命令来下载了，但是在网页和客户端是可以正常的访问。。😭

我也遇到了该问题，我的系统是 MAC， 我更换了windows 电脑就可以下载。

后续我在 mac 里删除了缓存文件夹，后续就可以下载了，命令如下

`rm -rf '/System/Volumes/Data/Users/your_name/Library/Application Support/geektime-downloader'`

**Comment by lonelystone545** [comment]
可以了感谢。感觉是个问题，楼主可以看下
