### ISSUE TITLE
pdf出现有空白字的情况

### ISSUE THREAD

**Issue by harochen75** [nicoxiang/geektime-downloader#151]
出现有空白的

**Comment by nicoxiang** [comment]
保持网络稳定，关闭VPN，适当调大 --wait-seconds 参数

**Comment by harochen75** [comment]
不是出现空白的页面，是出现部分文字pdf没有展示出来，实际是有文字的。  用ctrl+c复制到文本中是有文字的。
![image](https://github.com/nicoxiang/geektime-downloader/assets/88765180/4d496934-5adf-461a-9749-14f1aba9162a)

**Comment by harochen75** [comment]
> 保持网络稳定，关闭VPN，适当调大 --wait-seconds 参数

 试了，还是会出现相同的问题

**Comment by nicoxiang** [comment]
麻烦提供下课程名称和章节名称，我看下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月30日(周一) 下午2:44
收件人: ***@***.***&gt;;
抄送: "Nico ***@***.******@***.***&gt;;
主题: Re: [nicoxiang/geektime-downloader] pdf出现有空白字的情况 (Issue #151)




  
保持网络稳定，关闭VPN，适当调大 --wait-seconds 参数
  
试了，还是会出现相同的问题

**Comment by harochen75** [comment]
超级访谈：对话道哥  第一章。
AI绘画核心技术与实战，出现下载不了的情况，下完第一章会中断。

**Comment by nicoxiang** [comment]
> 超级访谈：对话道哥 第一章。 AI绘画核心技术与实战，出现下载不了的情况，下完第一章会中断。

有报错信息吗？方便提供一下吗？

**Comment by harochen75** [comment]
直接用的是exe,没看到报错的信息。
