### ISSUE TITLE
使用默认下载保存路径，下载了，但是没有保存下来

### ISSUE THREAD

**Issue by hiifong** [nicoxiang/geektime-downloader#16]

**Comment by hiifong** [comment]
> 是视频课吗？什么是下载了但没有保存下来，没太理解

就是下载视频课还有专栏PDF都没有保存下来

**Comment by hiifong** [comment]
> 指定下载保存路径可以保存

运行的时候指定-f参数就可以正常保存视频课还有PDF

**Comment by hiifong** [comment]
> 

哦哦，我以为是跟下载器在同一个文件夹下面，谢谢你的解答，也非常感谢你开发的工具，辛苦了

**Comment by nicoxiang** [comment]
> > 
> 
> 哦哦，我以为是跟下载器在同一个文件夹下面，谢谢你的解答，也非常感谢你开发的工具，辛苦了

谢谢你的建议，回头我修改下 README
