### ISSUE TITLE
ai绘画的课下不了，别的可以

### ISSUE THREAD

**Issue by jaimecai** [nicoxiang/geektime-downloader#160]
![Screenshot 2023-12-04 131551](https://github.com/nicoxiang/geektime-downloader/assets/10694130/4373804c-a80b-40a2-96f7-aa8193149d07)

_Originally posted by @jaimecai in https://github.com/nicoxiang/geektime-downloader/issues/127#issuecomment-1837863610_

**Comment by nicoxiang** [comment]
能否贴下 %AppData%\geektime-downloader\geektime-downloader.log 中的内容，只看截图看不出来是哪个接口超时了

**Comment by Camio1945** [comment]
这个专栏的图片太多了，把网页转成 pdf 的时候非常耗时，我改了源码，把 `context.Context` 的超时时间和 `-- wait-seconds` 参数都改成了10分钟(600秒)，也还是会超时。
目前我已经放弃了 pdf ，只是下载了 markdown 和音频。
解决办法是把 `--output 7` 改成 `--output 6`，未再出现超时问题（我没有开 vpn ）。
![Uploading Snipaste_2024-02-10_23-34-10.png…]()

**Comment by Camio1945** [comment]
这个专栏的图片太多了，把网页转成 pdf 的时候非常耗时，我改了源码，把 `context.Context` 的超时时间和 `-- wait-seconds` 参数都改成了10分钟(600秒)，也还是会超时。
目前我已经放弃了 pdf ，只是下载了 markdown 和音频。
**解决办法是把 `--output 7` 改成 `--output 6`**，未再出现超时问题（我没有开 vpn ）。

<img width="952" alt="Snipaste_2024-02-10_23-34-10" src="https://github.com/nicoxiang/geektime-downloader/assets/7963197/34312639-f99f-470c-847a-40e90d4e5c31">

**Comment by nicoxiang** [comment]
能否麻烦提供下章节的名字，我去看下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月10日(周六) 晚上11:44
收件人: ***@***.***&gt;;
抄送: "Nico ***@***.******@***.***&gt;;
主题: Re: [nicoxiang/geektime-downloader] ai绘画的课下不了，别的可以 (Issue #160)




 
这个专栏的图片太多了，把网页转成 pdf 的时候非常耗时，我改了源码，把 context.Context 的超时时间和 -- wait-seconds 参数都改成了10分钟(600秒)，也还是会超时。
 目前我已经放弃了 pdf ，只是下载了 markdown 和音频。
 解决办法是把 --output 7 改成 --output 6，未再出现超时问题（我没有开 vpn ）。
 Snipaste_2024-02-10_23-34-10.png (view on web)

**Comment by Camio1945** [comment]
> 能否麻烦提供下章节的名字，我去看下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月10日(周六) 晚上11:44 收件人: ***@***.***&gt;; 抄送: "Nico ***@***.******@***.***&gt;; 主题: Re: [nicoxiang/geektime-downloader] ai绘画的课下不了，别的可以 (Issue #160) 这个专栏的图片太多了，把网页转成 pdf 的时候非常耗时，我改了源码，把 context.Context 的超时时间和 -- wait-seconds 参数都改成了10分钟(600秒)，也还是会超时。 目前我已经放弃了 pdf ，只是下载了 markdown 和音频。 解决办法是把 --output 7 改成 --output 6，未再出现超时问题（我没有开 vpn ）。 Snipaste_2024-02-10_23-34-10.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我没有注意章节，直接就是下载的专栏下所有的文章，第一篇就卡住超时了。
