### ISSUE TITLE
视频课程id带有‘-’会提示课程ID不合法

### ISSUE THREAD

**Issue by 445990772** [nicoxiang/geektime-downloader#161]
情况一：https://time.geekbang.org/course/intro/100625601?utm_source=u_nav_web&utm_medium=u_nav_web&utm_term=u_nav_web&tab=catalog
输入课程ID：100625601
提示
![image](https://github.com/nicoxiang/geektime-downloader/assets/9440839/be832365-e4b3-44ea-9f46-ef3e3e8ddff4)
情况二
https://time.geekbang.org/course/detail/100625601-711617?utm_source=u_nav_web&utm_medium=u_nav_web&utm_term=u_nav_web
输入课程ID：100625601-711617
![image](https://github.com/nicoxiang/geektime-downloader/assets/9440839/a62c3f7b-317c-4d54-891d-c0dab86bb228)
![image](https://github.com/nicoxiang/geektime-downloader/assets/9440839/ef034457-87ac-4a6d-a273-6ae03e11a4d5)

**Comment by nicoxiang** [comment]
就输100625601，课程类型是普通课程，别选错

**Comment by 445990772** [comment]
好的 可以了
