### ISSUE TITLE
其他 下载不了？提示显示“输入的课程 ID 有误”？请大佬帮忙看看

### ISSUE THREAD

**Issue by Alex60105** [nicoxiang/geektime-downloader#165]
这两个其他课程 显示“输入的课程 ID 有误”...，但是在我的课程-其他列表里，麻烦大佬给看看
https://time.geekbang.org/column/intro/100035601?tab=catalog
https://time.geekbang.org/column/intro/100003001?tab=catalog
@nicoxiang

**Comment by nicoxiang** [comment]
这两个课的课程类型代码里还没做支持

目前支持的类型可以看下这块代码 [Support Types](https://github.com/nicoxiang/geektime-downloader/blob/main/cmd/root.go#L87-L92)

欢迎PR，或者可能要等等了，而且我的账户不一定有这种类型的课

**Comment by Capsule7446** [comment]
> 这两个课的课程类型代码里还没做支持
> 
> 目前支持的类型可以看下这块代码 [Support Types](https://github.com/nicoxiang/geektime-downloader/blob/main/cmd/root.go#L87-L92)
> 
> 欢迎PR，或者可能要等等了，而且我的账户不一定有这种类型的课

https://time.geekbang.org/column/article/181
请问一下这个课程不是普通课程嘛?
下载提示未登录

**Comment by nicoxiang** [comment]
> > 这两个课的课程类型代码里还没做支持
> > 目前支持的类型可以看下这块代码 [Support Types](https://github.com/nicoxiang/geektime-downloader/blob/main/cmd/root.go#L87-L92)
> > 欢迎PR，或者可能要等等了，而且我的账户不一定有这种类型的课
> 
> https://time.geekbang.org/column/article/181 请问一下这个课程不是普通课程嘛? 下载提示未登录

重新登录试试，不行的话把目录 %AppData%/geektime-downloader （MAC是$HOME/Library/Application Support/geektime-downloader）下存放用户的登录 cookie清掉，再重新登录试试。

**Comment by Capsule7446** [comment]
> > > 这两个课的课程类型代码里还没做支持
> > > 目前支持的类型可以看下这块代码 [Support Types](https://github.com/nicoxiang/geektime-downloader/blob/main/cmd/root.go#L87-L92)
> > > 欢迎PR，或者可能要等等了，而且我的账户不一定有这种类型的课
> > 
> > 
> > https://time.geekbang.org/column/article/181 请问一下这个课程不是普通课程嘛? 下载提示未登录
> 
> 重新登录试试，不行的话把目录 %AppData%/geektime-downloader （MAC是$HOME/Library/Application Support/geektime-downloader）下存放用户的登录 cookie清掉，再重新登录试试。

刚刚试了一下好像还是不行
![image](https://github.com/nicoxiang/geektime-downloader/assets/64939677/465a845b-6bc7-474e-aaf6-008d37608610)

**Comment by Capsule7446** [comment]
> @Capsule7446 课程ID输对了吗？左耳听风是100002201

我靠 大佬.我罪该万死.
我没有仔细看你的readme.
十分抱歉

**Comment by nicoxiang** [comment]
@Capsule7446 没事，有问题欢迎反馈
