### ISSUE TITLE
专栏列表加载不完整

### ISSUE THREAD

**Issue by hiifong** [nicoxiang/geektime-downloader#17]

**Comment by nicoxiang** [comment]
使用的版本是最新的吗？能稳定复现吗？

**Comment by hiifong** [comment]
> 使用的版本是最新的吗？能稳定复现吗？
是最新版，二进制版本。

**Comment by hiifong** [comment]
![1](https://user-images.githubusercontent.com/89133723/164474308-e976c1d7-59e9-479d-ae1d-5c3ccd8bbe25.png)
![2](https://user-images.githubusercontent.com/89133723/164474327-4a62ba39-219b-4ccf-a8f8-a16754f6edd8.png)

**Comment by hiifong** [comment]
不好意思看错了，打扰你了
