### ISSUE TITLE
公开课《行知数字中国》第二集下载不下来，公开课《C 位面对面》第一集下载不下来

### ISSUE THREAD

**Issue by Camio1945** [nicoxiang/geektime-downloader#176]
下载公开课[《行知数字中国》](https://time.geekbang.org/opencourse/videointro/100116801)第二集，或下载公开课[《C 位面对面》](https://time.geekbang.org/opencourse/videointro/100102301)第一集时，[这里](https://github.com/nicoxiang/geektime-downloader/blob/80cfe20a45a67149185cfda26a0247bea2893b93/internal/pkg/crypto/aes.go#L65)报错：panic: runtime error: index out of range [-1]

断点调试了一下，原因好像是因为 `vod.PlayInfo.Rand` 和 `vod.PlayInfo.Plaintext` 是空串，没有值。

**Comment by nicoxiang** [comment]
感谢分享，当然也欢迎pr。不行的话我后面看看怎么修这个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月11日(周一) 晚上6:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [nicoxiang/geektime-downloader] 公开课《行知数字中国》第二集下载不下来，公开课《C 位面对面》第一集下载不下来 (Issue #176)




 
下载公开课《行知数字中国》第二集，或下载公开课《C 位面对面》第一集时，这里报错：panic: runtime error: index out of range [-1]
 
断点调试了一下，原因好像是因为 vod.PlayInfo.Rand 和 vod.PlayInfo.Plaintext 是空串，没有值。
