### ISSUE TITLE
希望添加一键下载所有在学课程

### ISSUE THREAD

**Issue by hiifong** [nicoxiang/geektime-downloader#18]
要是能转换成Markdown格式就更加完美

**Comment by nicoxiang** [comment]
We will see if this feature is essential

**Comment by nicoxiang** [comment]
此功能有待商榷。因极客时间做了限流，要做到一次性下载完可以通过额外做多次自动登录实现，但多次登录可能又会触发登录接口的限流，如果要做可以看下有没有更好的办法。目前看实现成本收益不成比例。

**Comment by nicoxiang** [comment]
调整下载 PDF 间隔后下载更稳定了，不容易出现限流，可以重新考虑是否需要这个功能。

**Comment by hiifong** [comment]
> 调整下载 PDF 间隔后下载更稳定了，不容易出现限流，可以重新考虑是否需要这个功能。

可以把会员免费看的专栏视频全部下载吗？

**Comment by nicoxiang** [comment]
> > 调整下载 PDF 间隔后下载更稳定了，不容易出现限流，可以重新考虑是否需要这个功能。
> 
> 可以把会员免费看的专栏视频全部下载吗？

应该是可以实现的，大致思路是抓取用户是否是会员的标识，如果是会员多显示一个下载所有的选项。选择后抓取所有课程列表，筛选出其中有会员可以免费看的标志的课程，然后开始执行下载全部，同时需要统一下载视频和下载PDF的进度条展示界面（现在两者展示方式不同，因为生成PDF不方便显示进度），还要考虑中断下载后如何从上次下载的课程继续。这是一个不小的工作量，思路大概是这样，不过我最近没什么时间，欢迎大家的 PR~

**Comment by hiifong** [comment]
> > > 调整下载 PDF 间隔后下载更稳定了，不容易出现限流，可以重新考虑是否需要这个功能。
> > 
> > 
> > 可以把会员免费看的专栏视频全部下载吗？
> 
> ~应该是可以实现的，大致思路是抓取用户是否是会员的标识，如果是会员多显示一个下载所有的选项。选择后抓取所有课程列表，筛选出其中有会员可以免费看的标志的课程，然后开始执行下载全部，同时需要统一下载视频和下载PDF的进度条展示界面（现在两者展示方式不同，因为生成PDF不方便显示进度），还要考虑中断下载后如何从上次下载的课程继续。这是一个不小的工作量，思路大概是这样，不过我最近没什么时间，欢迎大家的 PR~
> 
> 算了我仔细的想了下，这个程序一开始还是为了个人学课程方便，支持这样大批量的下载并不是我的本意，甚至有可能会是出于传播的目的。所以我个人不希望加入这个功能，对希望有这个功能的朋友我很抱歉。

确实
