### ISSUE TITLE
请求超时，写不了日志，直接退出了

### ISSUE THREAD

**Issue by sunnymooni** [nicoxiang/geektime-downloader#188]
=================================
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument

Failed to write to log, invalid argument
[正在下载 开场致辞——让QCon的开发者先看到未来]  0 B / 89.64 MB [________________________________________] 0.00%
Failed to write to log, invalid argument
请求超时
==========================

**Comment by nicoxiang** [comment]
课程的名称和地址贴一下
