### ISSUE TITLE
密码输入错误次数过多，已触发验证码校验，请稍后再试

### ISSUE THREAD

**Issue by hiifong** [nicoxiang/geektime-downloader#19]
![image](https://user-images.githubusercontent.com/89133723/164909853-15b63945-b36e-4281-aac1-45d8d6b985aa.png)

**Comment by hiifong** [comment]
> ![image](https://user-images.githubusercontent.com/89133723/164909853-15b63945-b36e-4281-aac1-45d8d6b985aa.png)

网页版可以正常登录且不需要验证码

**Comment by nicoxiang** [comment]
暂时没搞清楚为什么网页登录和直接请求Api为什么会不一样，反正登陆过于频繁就会触发，尽量悠着点搞
