### ISSUE TITLE
视频下载异常

### ISSUE THREAD

**Issue by blue-dd** [nicoxiang/geektime-downloader#20]
[正在下载 05 | 微服务通信的济世良方：什么是Service Mesh？它能帮你做什么？]  8.31 MB / 85.96 MB [>__] 9.67%panic: context deadline exceeded (Client.Timeout or context cancellation while reading body)

goroutine 118 [running]:
github.com/nicoxiang/geektime-downloader/internal/video.writeToTempVideoFile(0x18327c0, 0xc00007ea00, 0xc0000b01e0, 0xc00015e0e0, 0xc0000a20b0, 0xc000434380, 0x3f, 0xc00042e5a0, 0x99)
	/Users/xxx/go/src/github.com/nicoxiang/geektime-downloader/internal/video/video.go:98 +0x4dc
github.com/nicoxiang/geektime-downloader/internal/video.DownloadVideo.func2(0x18327c0, 0xc00007ea00, 0xc0000b01e0, 0xc00015e0e0, 0xc0000a20b0, 0xc000434380, 0x3f, 0xc00042e5a0, 0x99)
	/Users/xxx/go/src/github.com/nicoxiang/geektime-downloader/internal/video/video.go:67 +0x8b
created by github.com/nicoxiang/geektime-downloader/internal/video.DownloadVideo
	/Users/xxx/go/src/github.com/nicoxiang/geektime-downloader/internal/video/video.go:66 +0x47e

**Comment by nicoxiang** [comment]
看起来是下载超时了，重试试试呢？这块还没做比较友好的提示，直接 panic 的，后面可以找时间调整下

**Comment by blue-dd** [comment]
重试有点问题，每次都卡在差不多百分比报异常。我改了下源码好像可以video.go.writeToTempVideoFile
resp, err := c.SetTimeout(time.Duration(1 * time.Minute)).R().

**Comment by nicoxiang** [comment]
嗯，我今天发个新版本，调大下超时，然后错误处理再优化下，感谢你提供的建议

**Comment by nicoxiang** [comment]
Try the new feature in [release 0.3.2](https://github.com/nicoxiang/geektime-downloader/releases/tag/v0.3.2)
