### ISSUE TITLE
Update 接口

### ISSUE THREAD

**Issue by hedeqiang** [nicoxiang/geektime-downloader#202]
极客时间最近貌似更新了接口，目前可能失效了，作者还会更新吗？

**Comment by SlamDunkDcc** [comment]
我遇到了登录不上

**Comment by nicoxiang** [comment]
用cookie方式登录试试呢？我看他们登录接口加了阿里的无痕验证

**Comment by LogicHou** [comment]
cookie可以下载，就是下载的时候会报错Failed to write to log, invalid argument但是是能下载成功

**Comment by nicoxiang** [comment]
> cookie可以下载，就是下载的时候会报错Failed to write to log, invalid argument但是是能下载成功

是用的最新版本的包吗？我记得这个报错我修过了的

**Comment by LogicHou** [comment]
> > cookie可以下载，就是下载的时候会报错Failed to write to log, invalid argument但是是能下载成功
> 
> 是用的最新版本的包吗？我记得这个报错我修过了的

是的，0.11.1

**Comment by chenao1** [comment]
老哥，我不知道怎么用cookie下载，有没有用cookie的教程啊？
还有 老哥，新的登录方式能搞得定吗？

**Comment by nicoxiang** [comment]
> 老哥，我不知道怎么用cookie下载，有没有用cookie的教程啊？ 还有 老哥，新的登录方式能搞得定吗？

看下README，传 --gcess --gcid 两个参数

**Comment by chenao1** [comment]
现在的问题 您打算修复吗？

**Comment by nicoxiang** [comment]
> 现在的问题 您打算修复吗？

有计划修复，但是最近实在没有空闲时间，如果你有办法欢迎PR

**Comment by chenao1** [comment]
我不会啊，老哥，哈哈哈！

**Comment by chenao1** [comment]
ERROR: could not unmarshal event: parse error: expected string near offset 986 of 'cookiePart...'一直报错这个，但是能下载。

**Comment by nicoxiang** [comment]
@chenao1 

> ERROR: could not unmarshal event: parse error: expected string near offset 986 of 'cookiePart...'

这个报错在0.11.2版本已修复
