### ISSUE TITLE
不知道怎么用，示例就一个登录，不知道怎么下载指定的课程id，是哪一个命令选项呢？

### ISSUE THREAD

**Issue by xl9612** [nicoxiang/geektime-downloader#210]
**Version**
e.g. 0.11.1

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log**
If applicable, add error log in folder %Appdata%/geektime-downloader

**Additional context**

**Comment by nicoxiang** [comment]
看下readme，另外现在不要用账号密码登录，用cookie登录

**Comment by CodeWater404** [comment]
浏览器网页登录之后，f12调出控制台，点击“应用”tab，找到cookie那里侧边栏，就可以看到gcid和gcess
