### ISSUE TITLE
可以在登陆时加上手机的区号吗？现在是固定了+86，海外电话需要手动改代码

### ISSUE THREAD

**Issue by JohnZhang3IoT** [nicoxiang/geektime-downloader#212]
**Version**
e.g. 0.11.1

**Comment by nicoxiang** [comment]
请问你是用账号密码登录的吗？我看最近他们已经加了滑动验证码，我尝试了下只能用cookie登录了

**Comment by JohnZhang3IoT** [comment]
> 请问你是用账号密码登录的吗？我看最近他们已经加了滑动验证码，我尝试了下只能用cookie登录了

是的，之前是用账号密码登录的，谢谢，用cookie登录成功了

**Comment by nicoxiang** [comment]
> > 请问你是用账号密码登录的吗？我看最近他们已经加了滑动验证码，我尝试了下只能用cookie登录了
> 
> 是的，之前是用账号密码登录的，谢谢，用cookie登录成功了

最近应该都已经不能用账号密码登录了，所以也不用加区号了，我先关issue了
