### ISSUE TITLE
下载课程时提示异常

### ISSUE THREAD

**Issue by Mydykitty** [nicoxiang/geektime-downloader#219]
使用geektime-downloader --gcid "XX" --gcess "XX"命令下载报错：

2024/10/18 15:13:12 ERROR: could not unmarshal event: parse error: expected string near offset 962 of 'cookiePart...'

能否辛苦帮忙看看

**Comment by nicoxiang** [comment]
是下载PDF的时候抛出的错误是吗

**Comment by Mydykitty** [comment]
是的，今天试了下就完全不可用了，报错我截了图，辛苦帮忙看下
<img width="1414" alt="图片" src="https://github.com/user-attachments/assets/5d8d2336-f934-4123-9202-deb4266507e5">

**Comment by nicoxiang** [comment]
@Mydykitty 小心不要暴露自己的cookie，问题我看到了，但是这个log的报错应该不影响正常使用的，我回去试试，你把软件的版本号发下

**Comment by Mydykitty** [comment]
github.com/nicoxiang/geektime-downloader@v0.11.1 现在用的是最新的版本

**Comment by nicoxiang** [comment]
@Mydykitty 
这个报错不影响正常使用的，你可以去文件夹里看看，应该PDF已经生成成功了，后面我升级下一个依赖就可以把报错去掉。

> 2024/10/18 15:13:12 ERROR: could not unmarshal event: parse error: expected string near offset 962 of 'cookiePart...'

**Comment by nicoxiang** [comment]
是不是还有其他的错误？也可以贴下，小心不要暴露自己的cookie。

**Comment by Mydykitty** [comment]
> @Mydykitty 这个报错不影响正常使用的，你可以去文件夹里看看，应该PDF已经生成成功了，后面我升级下一个依赖就可以把报错去掉。
> 
> > 2024/10/18 15:13:12 ERROR: could not unmarshal event: parse error: expected string near offset 962 of 'cookiePart...'

这个PDF确实生成成功了，不过有的PDF打开为空 3-4个PDF中有一个为空，不过这是之前产生的问题，不能再复现了。

现在产生的问题是直接报错，无法进行任何下载，错误截图如下（第一张截图输入了课程ID后产生了第二张截图的错误）：
<img width="772" alt="image" src="https://github.com/user-attachments/assets/96ec1bbe-bd1a-42cd-ad4c-d75bb899b566">
<img width="772" alt="image" src="https://github.com/user-attachments/assets/10e0e44b-44e5-4e41-b12c-621baaff0da8">

**Comment by nicoxiang** [comment]
@Mydykitty 试试最新的0.11.2版本，应该都消除掉上面的报错，有的PDF打开为空的问题可以试试单个文章重新下载，如果还是不行，试试调大--print-pdf-wait参数
