### ISSUE TITLE
希望可以添加能够下载的资源列表

### ISSUE THREAD

**Issue by Finalweapons** [nicoxiang/geektime-downloader#22]
希望增加可下载资源列表功能和一键下载，类似geektime-dl
感谢大佬创作的工具

**Comment by Finalweapons** [comment]
另外在下载完毕后希望可以刷新一下已学习课程列表

**Comment by nicoxiang** [comment]
可下载资源指的是什么？你可以选择你买过的专栏和视频课，和选择专栏和视频课里面的文章，视频。一键下载这个其实现在看下来没什么意义，因为极客时间做了限流，没法一次性下载完，你可以试试geektime dl，下载的pdf有空白就是这个原因

**Comment by nicoxiang** [comment]
刷新已学习这个功能估计实现起来不简单，收益看起来不大

**Comment by Finalweapons** [comment]
> 刷新已学习这个功能估计实现起来不简单，收益看起来不大

Emmmmm,我指的是下载完以后可以重新获取一下已学习的内容。
我在等待下载完成的时候去极客时间看了几篇新专栏，但是下载完以后显示的还是之前的内容，需要重启软件刷新

**Comment by nicoxiang** [comment]
这个列表当时考虑的全局指加载一次的，这样不用每次展示列表都请求接口。可以考虑下看类似的需求多不多，感谢建议😊。

**Comment by nicoxiang** [comment]
可下载资源列表应该有显示吧？ @Finalweapons

**Comment by Finalweapons** [comment]
> 可下载资源列表应该有显示吧？ @Finalweapons

现在显示的是已学习的列表，就是需要先点开看过一次才可以。不过不知道为什么我这里不能记住登录状态，每次必须都得用登录参数登录一下才行

**Comment by nicoxiang** [comment]
应该只要在极客时间的[这个页面](https://time.geekbang.org/dashboard/course)有的就会出现在列表中，看下向下滚动列表看看有没有。登录状态只要用账号登录的都会记住，下次不用输入密码，cookie登录的是不会记的。

**Comment by Finalweapons** [comment]
> 应该只要在极客时间的[这个页面](https://time.geekbang.org/dashboard/course)有的就会出现在列表中，看下向下滚动列表看看有没有。登录状态只要用账号登录的都会记住，下次不用输入密码，cookie登录的是不会记的。

我这里每次使用都需要-u指定手机号然后输密码才行。。。

**Comment by nicoxiang** [comment]
那就有问题了，是什么系统，windows吗？如果是的话能否帮忙看下 %Appdata%/geektime-downloader目录下有没有生成配置文件？

**Comment by Finalweapons** [comment]
Win10 21H2 专业工作站版 这个目录是空的

**Comment by nicoxiang** [comment]
我本地没有复现，我会新开一个 issue，看下其他人有没有类似的问题，也欢迎 PR，相关代码位置[点此](https://github.com/nicoxiang/geektime-downloader/blob/main/internal/pkg/file/file.go#L115)
