### ISSUE TITLE
An error occurred: Head   An error occurred: open ...

### ISSUE THREAD

**Issue by chenbihao** [nicoxiang/geektime-downloader#227]
**Version**
e.g. 0.11.2

**Describe the bug**

`An error occurred: Head "https://source.unsplash.com/200x200/?<`word` in English>": EOF`
`An error occurred: open E:\Download\零基础GPT应用入门课\images\667888\?<关键词>: The filename, directory name, or volume label syntax is incorrect.`

**To Reproduce**

id:100550701    零基础GPT应用入门课 

错误章节 08/20、10/20 等

**Expected behavior**

**Screenshots**

**Log**

`[2024-11-23 23:50:29] [info] [client.go:102] Http request end, method: POST, url: https://time.geekbang.org/serv/v1/article, status code: 200
[2024-11-23 23:50:37] [error] [root.go:441] An error occurred`

**Additional context**

如果可以的话可以试试整个课程，这个课程遇到的错误比较多

**Comment by nicoxiang** [comment]
已在0.12.1版本修复
