### ISSUE TITLE
An error occurred: Head "https://xx/lib.rs": dial tcp xx:443: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by L-Super** [nicoxiang/geektime-downloader#228]
**Version**
0.11.2

**Describe the bug**
powershell output:
```bash
[ 正在下载 《43｜生产环境：真实世界下的一个Rust项目包含哪些要素？》... ]◢An error occurred: Head "https://github.com/tokio-rs/bytes/blob/master/src/lib.rs": dial tcp 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it.
```
**To Reproduce**
1. cookie登录
2. 下载100085301课程
3. 中途报了好几次这个错

**Log**
[geektime-downloader.log](https://github.com/user-attachments/files/17891343/geektime-downloader.log)

**Additional context**
Windows 11 powershell 7.4.6

**Comment by L-Super** [comment]
然后重试下载，终端输出：
```bash
已完成下载39/65
已触发限流, 你可以选择重新登录/重新获取 cookie, 或者稍后再试, 然后生成剩余的文章
```
跳过当前下载其他文章，正常。怀疑个别文章解析有问题？

**Comment by nicoxiang** [comment]
感谢提供错误，简单看了眼应该是markdown解析有问题，过段时间我看下最近有点忙

**Comment by nicoxiang** [comment]
已在0.12.1版本修复
