### ISSUE TITLE
密码登录情况下，登录状态未保存

### ISSUE THREAD

**Issue by nicoxiang** [nicoxiang/geektime-downloader#23]
系统： windows

现象：配置文件目录 %AppData%/geektime-downloader 下未生成保存登录状态的文件。本机未复现，但在其他用户电脑出现

see #22

**Comment by Finalweapons** [comment]
操作环境的是Vscode PowerShell

**Comment by nicoxiang** [comment]
在多台设备使用相同的操作系统，并使用不同用户均未复现，先暂时标记 invalid
