### ISSUE TITLE
已下载完的重复下载未能直接跳过

### ISSUE THREAD

**Issue by Finalweapons** [nicoxiang/geektime-downloader#25]
![geektime报错](https://user-images.githubusercontent.com/53458682/167098718-c152591a-8799-40c4-9ab7-ce09e8d176de.png)
如图，其他课程下载完毕后再点击下载全部视频会直接跳过，但是这个微信小程序的不知道为什么会一直重复下载这几个视频

**Comment by nicoxiang** [comment]
Thanks for your feedback :) 
This bug has been fixed in [v0.3.3](https://github.com/nicoxiang/geektime-downloader/releases/tag/v0.3.3)
