### ISSUE TITLE
可以支持不下载评论吗？

### ISSUE THREAD

**Issue by amwps290** [nicoxiang/geektime-downloader#29]

**Comment by nicoxiang** [comment]
很不错的建议，有些课程的确评论很长。但是有些抱歉短期内应该还没法添加这个功能到下个 release，我可以先开始尝试 coding。感谢建议。

**Comment by nicoxiang** [comment]
--comments 参数在新版本[ v0.4.2](https://github.com/nicoxiang/geektime-downloader/releases/tag/v0.4.2) 版本已经可用
