### ISSUE TITLE
希望 增加支持训练营课程视频下载的功能

### ISSUE THREAD

**Issue by GreeyiSaEs** [nicoxiang/geektime-downloader#35]
1.目前只支持下载专栏的视频  训练营的方法应该差不多 希望增加
2。pdf目前下载的评论看不到折叠的评论  能够支持将一个评论里的多条回复全部展开吗
3. 支持html形式下载专栏   目前PDF形式如果是代码块的话 经常因为代码过长不能滑动导致显示不全

谢谢大佬

**Comment by nicoxiang** [comment]
首先感谢你的宝贵建议！

1. 我的个人账号没有训练营，所以不太清楚训练营课程的接口是什么样的，欢迎有训练营账号的同学的 PR，只要底层内容形式都是普通课程那样的文章或者视频，下载的方法都是可以复用的。
2. 如果是主评论过长收起来了，这种情况可以通过 js 模拟点击“展开”按钮展开评论。但是下面的跟评在页面（Ipad设备下）上点击后会新打开页面，这个暂时不能很简单的通过 js 模拟动作完成加载，需要考虑别的办法。
<img width="215" alt="屏幕截图 2022-05-29 120953" src="https://user-images.githubusercontent.com/11958087/170852516-2a18258a-2c89-402d-8e67-2507948fb03f.png">

3. 代码过长的问题也不能通过操作 js 达到显示所有的目的，至于生成 HTML 我找了一些其他的下载器，生成的 HTML 也是没法滚动的，@GreeyiSaEs 你那边有看到其他库有达到支持滚动效果的吗？我可以去参考下。另一个问题是如果只是为了这一个功能要新增一种下载文件格式，也有点麻烦（有些人有些时候只能看 PDF但是想 看代码又只能切回 HTML），暂时没有想到两全的办法。

**Comment by hiifong** [comment]
> 首先感谢你的宝贵建议！
> 
> 
> 
> 1. 我的个人账号没有训练营，所以不太清楚训练营课程的接口是什么样的，欢迎有训练营账号的同学的 PR，只要底层内容形式都是普通课程那样的文章或者视频，下载的方法都是可以复用的。
> 
> 2. 如果是主评论过长收起来了，这种情况可以通过 js 模拟点击“展开”按钮展开评论。但是下面的跟评在页面（Ipad设备下）上点击后会新打开页面，这个暂时不能很简单的通过 js 模拟动作完成加载，需要考虑别的办法。
> 
> <img width="215" alt="屏幕截图 2022-05-29 120953" src="https://user-images.githubusercontent.com/11958087/170852516-2a18258a-2c89-402d-8e67-2507948fb03f.png">
> 
> 
> 
> 3. 代码过长的问题也不能通过操作 js 达到显示所有的目的，至于生成 HTML 我找了一些其他的下载器，生成的 HTML 也是没法滚动的，@GreeyiSaEs 你那边有看到其他库有达到支持滚动效果的吗？我可以去参考下。另一个问题是如果只是为了这一个功能要新增一种下载文件格式，也有点麻烦（有些人有些时候只能看 PDF但是想 看代码又只能切回 HTML），暂时没有想到两全的办法。
> 
> 
> 
> 

可以考虑保存为markdown文件吗？

**Comment by GreeyiSaEs** [comment]
@nicoxiang 用Chrome的插件保存整个网页是可以的 比如singlefile

**Comment by nicoxiang** [comment]
这个插件是ok的，但是得看下如何用编程的方式即通过chromedp实现，不一定方便做

**Comment by nicoxiang** [comment]
@hiifong 我后面看下 github.com/JohannesKaufmann/html-to-markdown 这个插件，我看到有些工具用了这个，可以试试

**Comment by GreeyiSaEs** [comment]
@nicoxiang 大佬 我刚刚试用cookie的形式登录企业微信版极客账号  我先在网页登录后拿到gcid 和gcess后用·downloader登录 会显示“当前账户在其他设备登录或者登录已经过期, 请尝试重新登录“

**Comment by nicoxiang** [comment]
@GreeyiSaEs 请教下，你说的企业微信版极客时间账号是不是账号名不是手机，是一串公司给的数字，然后登录入口和普通账号一样的那种？我朋友有个这种账号，我不知道是不是和你的一样，如果一样我明天拿他账号试下，普通账号cookie登录应该没问题的

**Comment by nicoxiang** [comment]
> @hiifong 我后面看下 github.com/JohannesKaufmann/html-to-markdown 这个插件，我看到有些工具用了这个，可以试试

@hiifong 我试用了下确实能看得到完整的代码，但是 markdown 的阅读体验还是没法和原生的极客时间样式相比。如果又要 PDF 又要显示完整的代码，这就很棘手了。

**Comment by hiifong** [comment]
> 

使用sel只保存正文的部分阅读体验应该还可以吧,遇到图片的话可以保存到本地，再用正则修改相对地址。

**Comment by hiifong** [comment]
> > @hiifong 我后面看下 github.com/JohannesKaufmann/html-to-markdown 这个插件，我看到有些工具用了这个，可以试试
> 
> @hiifong 我试用了下确实能看得到完整的代码，但是 markdown 的阅读体验还是没法和原生的极客时间样式相比。如果又要 PDF 又要显示完整的代码，这就很棘手了。

使用sel只保存正文的部分阅读体验应该还可以吧,遇到图片的话可以保存到本地，再用正则修改相对地址。

**Comment by nicoxiang** [comment]
@hiifong 我找到了[这个仓库](https://github.com/duc-cnzj/geekbang2md)，肯定是能做到的，但是显示效果你可以试下，markdown 说实话是有点素的…你如果有需求可以试下他这个库。

**Comment by nicoxiang** [comment]
@hiifong 当然如果确实很多人有这个需求，加到现在的程序里应该也挺快的

**Comment by hiifong** [comment]
> @hiifong 我找到了[这个仓库](https://github.com/duc-cnzj/geekbang2md)，肯定是能做到的，但是显示效果你可以试下，markdown 说实话是有点素的…你如果有需求可以试下他这个库。

不过这应该很符合程序员的审美吧，还有markdown可以保留原文的存在的各类链接，这个链接有时候还是比较重要的

**Comment by nicoxiang** [comment]
@hiifong [新版本 0.5.1](https://github.com/nicoxiang/geektime-downloader/releases/tag/v0.5.1) 已经支持了可以下载专栏为 Markdown 格式，欢迎更多建议。

@GreeyiSaEs 展开评论的功能忘了这个版本带上了，可以在下个小版本再加，如果显示跟评暂时还没有好的思路。

**Comment by nicoxiang** [comment]
已拆分出两个新 issue，暂时关闭此 issue
