### ISSUE TITLE
支持训练营课程的下载

### ISSUE THREAD

**Issue by nicoxiang** [nicoxiang/geektime-downloader#42]
from #35 

我的个人账号没有训练营，所以不太清楚训练营课程的接口是什么样的，欢迎有训练营账号的同学的 PR，只要底层内容形式都是普通课程那样的文章或者视频，下载的方法都是可以复用的。

**Comment by BeatsKitano** [comment]
还剩余14天

**Comment by nicoxiang** [comment]
@BeatsKitano 我简单看了下训练营里的视频，加密方式还和普通课程不太一样，普通视频 m3u8 地址在课程信息里能直接拿到，做一层解码就能下载了，但是训练营的还另外调了一个认证接口才能拿到完整的 m3u8 地址，而且这个认证接口很复杂，要找别的方法拿 m3u8 地址，不巧我最近空闲时间太少了，应该是没法在15天内搞定这个功能了。后面等有空了我再花时间看下，反正他们视频这块都是用的阿里的服务。

**Comment by nicoxiang** [comment]
而且我不清楚训练营是不是都是视频形式的，目前来说我只看到视频的。

**Comment by BeatsKitano** [comment]
没事的，账号随意用

**Comment by yandexxx123** [comment]
@nicoxiang 大佬你好，其实体验课和训练营是一样的入口：https://u.geekbang.org/schedule
希望可以增加这个下载支持，这样就不用担心体验课过期问题了。

**Comment by BeatsKitano** [comment]
账号已续费一年。放心使用

**Comment by nicoxiang** [comment]
@BeatsKitano @yandexxx123 感谢支持，后面会好好研究下的

**Comment by zivfuture** [comment]
请问有进展吗？

**Comment by zivfuture** [comment]
@nicoxiang

**Comment by nicoxiang** [comment]
@zivfuture  已经在coding了，测试下来是可以实现的，代码和细节要再优化下，中秋左右应该能出一版

**Comment by zivfuture** [comment]
@nicoxiang   感谢，是否需要捐献？  支持意思一下

**Comment by zivfuture** [comment]
我想问一下， 大家下载的课都是真的买了的吗？

**Comment by zivfuture** [comment]
里面有些课我买了不少， 但也借着体验的机会剽了一些，  训练营你们怎么下载的？ @GreeyiSaEs  @yandexxx123

**Comment by nicoxiang** [comment]
版本 0.8.1 已支持训练营课程下载，目前仅支持视频的下载，使用方式详见 README。欢迎问题反馈。

**Comment by zivfuture** [comment]
@nicoxiang   能否加个Q?
