### ISSUE TITLE
视频下载出现连接错误

### ISSUE THREAD

**Issue by bambooslipsec** [nicoxiang/geektime-downloader#44]
n error occurred: Get "https://media001.geekbang.org/2b67e6717d5d49b49a4fd1b220588a1b/d000806f075d49a34f930f43e3a10598-ld-encrypt-stream-00028.ts": dial tcp 112.19.5.225:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
发生 n 个错误: 获取“ https://media001.geekbang.org/2b67e6717d5d49b49a4fd1b220588a1b/d000806f075d49a34f930f43e3a10598-ld-encrypt-stream-00028.ts”: 拨打 tcp 112.19.5。225:443: connectex: 连接尝试失败，因为连接的一方在一段时间后没有正确响应，或者建立的连接失败，因为连接的主机没有响应。 
视频下载出现这种错误，每次下载都会出现连接错误，如果重新下载，问题依旧，能不能调节一下设置，防止连接失败。

**Comment by nicoxiang** [comment]
是不是在有代理的情况下下载的，这应该是网络问题都连不上对方 server 了，设置应该是没什么问题的了
