### ISSUE TITLE
Markdown图片引用路径有误！

### ISSUE THREAD

**Issue by hiifong** [nicoxiang/geektime-downloader#47]
![image](https://user-images.githubusercontent.com/89133723/175755194-fd1ca27a-0c5c-4303-ab8f-5c1f8ce10c87.png)
![image](https://user-images.githubusercontent.com/89133723/175755206-5f1781cd-a96a-422f-8f8f-7adb8b510a1a.png)
路径是使用`\`，在github上无法引用图片资源。需要修改为`/`。

**Comment by nicoxiang** [comment]
这个是根据使用程序的平台决定的，如果你在 linux 平台下使用这个工具下载，会发现相对路径就是 images/...  这个我觉得没什么问题

**Comment by hiifong** [comment]
> 这个是根据使用程序的平台决定的，如果你在 linux 平台下使用这个工具下载，会发现相对路径就是 images/... 这个我觉得没什么问题

统一使用`/`兼容性会更好些

**Comment by nicoxiang** [comment]
v0.7.1 版本已修复
