### ISSUE TITLE
已完成下载41/44An error occurred: Get "": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by WXY8888** [nicoxiang/geektime-downloader#49]
部分音频下载时会报错。

正在下载专栏 《Java核心技术面试精讲》 中的所有文章
已完成下载41/44An error occurred: Get "": unsupported protocol scheme ""

**Comment by nicoxiang** [comment]
哈哈，这一课应该是没音频的，好像是漏判空了回头我修下，可以这几课先别下载音频，感谢feedback



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月2日(周六) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [nicoxiang/geektime-downloader] 已完成下载41/44An error occurred: Get "": unsupported protocol scheme "" (Issue #49)




 
部分音频下载时会报错。
 
正在下载专栏 《Java核心技术面试精讲》 中的所有文章
 已完成下载41/44An error occurred: Get "": unsupported protocol scheme ""

**Comment by nicoxiang** [comment]
已修复，会在后续新版本带上
