### ISSUE TITLE
Always Timeout for PDF Download

### ISSUE THREAD

**Issue by FingerNFT** [nicoxiang/geektime-downloader#50]
e.g. for course 100006601

![image](https://user-images.githubusercontent.com/109035186/178153220-024f39f7-2c7e-4ec7-adf8-a6a61cddf6c3.png)

**Comment by FingerNFT** [comment]
![image](https://user-images.githubusercontent.com/109035186/178153327-4266d96b-59e0-4e71-9bee-40d2a1decffb.png)

**Comment by FingerNFT** [comment]
Video course can be download w/o any blocking issues.

**Comment by nicoxiang** [comment]
如果已安装 chrome 并且网络状况良好，请尝试重试。pdf 的下载是通过启动后台 chrome 进程完成的，有时候会出现生成超时的情况，这取决于 chrome 进程的情况，正常是没问题的。

**Comment by nicoxiang** [comment]
如果一直有问题，可以继续在这边回复
