### ISSUE TITLE
command not found: geektime-downloader.exe

### ISSUE THREAD

**Issue by ChengGuang-Li** [nicoxiang/geektime-downloader#59]
请问大佬们,这个应该怎么办?  我实在是搞不懂为啥，go的配置不对？

我的操作
1. clone 项目到本地
2. cd geektime-downloader
3. go install github.com/nicoxiang/geektime-downloader@latest
4. geektime-downloader.exe -h

报错: 
 zsh: command not found: geektime-downloader.exe

**Comment by nicoxiang** [comment]
什么系统？ 如果本地有go的环境，直接 go install 不用clone项目，或者clone项目然后 go build 也可以，这是go的操作问题。如果对go不熟悉，可以直接在 releases页面下载对应系统的二进制可执行文件。

**Comment by ChengGuang-Li** [comment]
谢谢大佬回复。 我是Mac系统。 确实没接触过go🤣。 
但是我看 我的路径 ~/go/bin 下面有  geektime-downloader。 我需要先把这个文件给删除吗？ 
<img width="366" alt="Screen Shot 2022-09-04 at 13 09 31" src="https://user-images.githubusercontent.com/54140371/188298457-4683ac8d-5623-4ba6-b865-3e0d2d6fb6bb.png">

**Comment by ChengGuang-Li** [comment]
1. 我先删除~/go/bin 下面的geektime-downloader
2. 我通过 go install github.com/nicoxiang/geektime-downloader@latest 安装。
3. 运行 geektime-downloader.exe -h， 还错报错 zsh: command not found: geektime-downloader.exe😭

**Comment by ChengGuang-Li** [comment]
1. 使用二进制文件，下载，解压完以后。 
2. 在terminal 里面点不动，也没办法ctrl + c 终止。新开一个terminal 运行 geektime-downloader.exe -h， 还错报错 zsh: command not found: geektime-downloader.exe。 
请问这种如何操作啊？ 大佬 🙏🏻

**Comment by nicoxiang** [comment]
mac 可以去 release 页面找 darwin 的包安装

**Comment by ChengGuang-Li** [comment]
> mac 可以去 release 页面找 darwin 的包安装

是的，我用的就是darwin 安装包。 是不是要把下下来的二进制文件放到PATH 目录下。

**Comment by ChengGuang-Li** [comment]
> > mac 可以去 release 页面找 darwin 的包安装
> 
> 是的，我用的就是darwin 安装包。 是不是要把下下来的二进制文件放到PATH 目录下。

1.我把下载的二进制文件放到了 ~/go/bin 下面。 还是报错 zsh: command not found: geektime-downloader.exe。  
但是我的lux 就可以正常运行。 
<img width="264" alt="Screen Shot 2022-09-04 at 14 25 52" src="https://user-images.githubusercontent.com/54140371/188300507-46f76c48-12d3-40e7-8b03-b5388ba7446c.png">

**Comment by nicoxiang** [comment]
不需要指定PATH，也需要 go 环境，下载完 darwin 包以后 terminal cd 进当前目录， tar 命令解压缩，然后 mac 执行可执行文件直接用 ./geektime-downloader  执行，不要加.exe，那是windows的可执行文件后缀，linux 和 mac 不需要后缀

**Comment by ChengGuang-Li** [comment]
> 不需要指定PATH，也需要 go 环境，下载完 darwin 包以后 terminal cd 进当前目录， tar 命令解压缩，然后 mac 执行可执行文件直接用 geektime-downloader 执行，不要加.exe，那是windows的可执行文件后缀，linux 和 mac 不需要后缀

还是不行😭  真的好奇怪。

**Comment by ChengGuang-Li** [comment]
> > 不需要指定PATH，也需要 go 环境，下载完 darwin 包以后 terminal cd 进当前目录， tar 命令解压缩，然后 mac 执行可执行文件直接用 geektime-downloader 执行，不要加.exe，那是windows的可执行文件后缀，linux 和 mac 不需要后缀
> 
> 还是不行😭 真的好奇怪。 有go环境， 我的lux 就可以用。
