### ISSUE TITLE
专栏中包含的视频未下载

### ISSUE THREAD

**Issue by zivfuture** [nicoxiang/geektime-downloader#60]
某些专栏中包含一些视频， 但是发现没有将其中的视频下载下来：
![image](https://user-images.githubusercontent.com/49356505/189255847-0d577eed-67c4-40e4-9695-b54e3a3fcf77.png)

**Comment by nicoxiang** [comment]
课程名或者课程 ID 分享一下。现在是做成专栏只下载文章PDF的。

**Comment by zivfuture** [comment]
@nicoxiang   100114501

**Comment by nicoxiang** [comment]
这应该是新的课程形式，文章中夹带视频，以前的专栏应该是只包含图文的，这门课是新课。这是一个待解决的新需求。感谢分享。

**Comment by GreeyiSaEs** [comment]
@nicoxiang 大佬 这个形式现在一些新课确实会有，又有图文还有内嵌的视频，然后每日一课和大厂案例是不是也和训练营一样的下载方法，大佬有空时能增加支持吗😬

**Comment by nicoxiang** [comment]
> @nicoxiang 大佬 这个形式现在一些新课确实会有，又有图文还有内嵌的视频，然后每日一课和大厂案例是不是也和训练营一样的下载方法，大佬有空时能增加支持吗😬

会做考虑的，谢谢~

**Comment by nicoxiang** [comment]
> @nicoxiang 大佬 这个形式现在一些新课确实会有，又有图文还有内嵌的视频，然后每日一课和大厂案例是不是也和训练营一样的下载方法，大佬有空时能增加支持吗😬

每日一课和大厂案例 supported since v0.9.1
文字视频交替的课程下载计划下个版本支持

**Comment by nicoxiang** [comment]
文字视频交替的课程下载功能 supported since v0.9.2
