### ISSUE TITLE
下载总是超时，并且每次都要重复步骤？

### ISSUE THREAD

**Issue by L-Super** [nicoxiang/geektime-downloader#65]
总是下载超时，不知道是不是反爬虫机制。
超时后，都需要这样做吗？

```
.\geektime-downloader.exe -u ""
 x 请输入课程 ID: █
```
如果我操作方式正确的话，这方面能不能优化一下逻辑，直接
```
.\geektime-downloader.exe -u "" -id "课程id"
```
这样方便一些？

**Comment by nicoxiang** [comment]
好建议。另外下载超时日志能否提供下？windows 应该在  %AppData%\geektime-downloader  下的 log 文件里。网络正常情况应该不会超时，反爬虫会有额外的错误输出的

**Comment by L-Super** [comment]
time="2022-09-22T15:17:46+08:00" level=error msg="An error occurred" func=github.com/nicoxiang/geektime-downloader/internal/pkg/logger.Error file="github.com/nicoxiang/geektime-downloader/internal/pkg/logger/logger.go:58" error="unknown shorthand flag: '2' in -2"
time="2022-09-22T15:17:56+08:00" level=error msg="An error occurred" func=github.com/nicoxiang/geektime-downloader/internal/pkg/logger.Error file="github.com/nicoxiang/geektime-downloader/internal/pkg/logger/logger.go:58" error="unknown shorthand flag: '2' in -2"
time="2022-09-22T15:19:58+08:00" level=error msg="Request Timeout" func=github.com/nicoxiang/geektime-downloader/internal/pkg/logger.Error file="github.com/nicoxiang/geektime-downloader/internal/pkg/logger/logger.go:58" error="context deadline exceeded (Client.Timeout or context cancellation while reading body)"
time="2022-09-22T15:25:57+08:00" level=error msg="Request Timeout" func=github.com/nicoxiang/geektime-downloader/internal/pkg/logger.Error file="github.com/nicoxiang/geektime-downloader/internal/pkg/logger/logger.go:58" error="context deadline exceeded (Client.Timeout or context cancellation while reading body)"
time="2022-09-22T15:39:27+08:00" level=error msg="Request Timeout" func=github.com/nicoxiang/geektime-downloader/internal/pkg/logger.Error file="github.com/nicoxiang/geektime-downloader/internal/pkg/logger/logger.go:58" error="context deadline exceeded (Client.Timeout or context cancellation while reading body)"

**Comment by nicoxiang** [comment]
`.\geektime-downloader.exe -u "" -id "课程id"`

这个我后面想了下，之前我考虑过这种做法。当时提供输入的原因是填完课程 id 后进入下一个选择列表后可以返回上一级重新输入课程id，并且下载某个课程的所有文字/视频后也可以重新输入课程id，不用重启命令行，所以当时做了这样的设计。

**Comment by nicoxiang** [comment]
context deadline exceeded (Client.Timeout or context cancellation while reading body)

这个就是标准下载超时的输出，看不出来具体的原因，网络不好的情况都是出现，暂时不太好排查，如果有比较好的建议可以提出来，感谢。

**Comment by L-Super** [comment]
> `.\geektime-downloader.exe -u "" -id "课程id"`
> 
> 这个我后面想了下，之前我考虑过这种做法。当时提供输入的原因是填完课程 id 后进入下一个选择列表后可以返回上一级重新输入课程id，并且下载某个课程的所有文字/视频后也可以重新输入课程id，不用重启命令行，所以当时做了这样的设计。

但实际体验并不好，因为下载较多节数专栏时，容易触发限流等问题，就需要重新登录。于是

**Comment by nicoxiang** [comment]
> > `.\geektime-downloader.exe -u "" -id "课程id"`
> > 这个我后面想了下，之前我考虑过这种做法。当时提供输入的原因是填完课程 id 后进入下一个选择列表后可以返回上一级重新输入课程id，并且下载某个课程的所有文字/视频后也可以重新输入课程id，不用重启命令行，所以当时做了这样的设计。
> 
> 但实际体验并不好，因为下载较多节数专栏时，容易触发限流等问题，就需要重新登录。于是

嗯，这个确实是个不好的点，我再考虑下，感谢建议。

**Comment by L-Super** [comment]
> 

话还没说完，就误发出去了😂，希望能看到完整回复

**Comment by nicoxiang** [comment]
限流 - 重新执行命令行

这个其实是记住 cookie 的，只是代码里做了清除保存的 cookie，重新输入密码才记录新 cookie，如果不要求用户输入，会出现这样的情况：
1. 首次输入密码，保存 cookie 到本地
2. 退出程序
3.第二次进入程序，不需要输入密码，使用 cookie 登录
4.发生限流
5.此时无法读到密码，只能读到旧 cookie，所以无法重新生成新 cookie，所以这里才会要求重新输入密码

我也不想直接把密码存本地，这肯定不安全
