### ISSUE TITLE
建议下载完成后提示已完成

### ISSUE THREAD

**Issue by L-Super** [nicoxiang/geektime-downloader#66]
当我下载完一门课时，并没给出下载完成的提示，而我也无法确定是否下载成功还是失败，也担心是否有漏下的才没有成功的提示
```
正在下载专栏 《许式伟的架构课》 中的所有文章
x 请输入课程 ID: █
```

**Comment by nicoxiang** [comment]
漏下或者中途失败都会弹出错误信息并终止，尝试重新下载就可以了，如果没有报错就是下载全部成功。
