### ISSUE TITLE
希望可以转成电子书epub格式

### ISSUE THREAD

**Issue by hiifong** [nicoxiang/geektime-downloader#77]
![Screenshot_20221113_105856_com.tencent.weread.jpg](https://user-images.githubusercontent.com/89133723/201503549-dd1c229e-dd5a-4cc3-8a18-5b6fda090818.jpg)
方便导入微信图书学习

**Comment by hiifong** [comment]
@nicoxiang 大佬这个有计划？

**Comment by nicoxiang** [comment]
暂时没有，在线pdf转epub的挺多的，直接用就好
