### ISSUE TITLE
希望下载的静态资源按序号命名

### ISSUE THREAD

**Issue by hiifong** [nicoxiang/geektime-downloader#80]
![image](https://user-images.githubusercontent.com/89133723/205553804-b72616a9-a558-428d-92a6-70b30bf0e6d7.png)
例如这张图片是这篇专栏的第一讲的第一张的图谱那么就命名为`images/1/1.png`

**Comment by nicoxiang** [comment]
images/605398/1.jpg 这样应该可以，中间一段是文章id，不要替换后缀名。我觉得是可以的，方便提一个PR吗？
