### ISSUE TITLE
ts转mp4

### ISSUE THREAD

**Issue by pure-maple** [nicoxiang/geektime-downloader#85]
视频课下载的ts文件是否可以转为MP4，尝试用ffmpeg转换出现异常，是因为加密的原因吗？

**Comment by nicoxiang** [comment]
我试了下也有些报错，但是最后能转成功，也能正常播放。大部分播放器应该能直接播放ts 格式。
ffmpeg的命令我网上随便找的，应该有其他更合适的参数：

`ffmpeg -i yourvideoname.ts -c:v libx264 outputfilename.mp4`
