### ISSUE TITLE
无法下载『左耳听风』专栏

### ISSUE THREAD

**Issue by Camio1945** [nicoxiang/geektime-downloader#87]
专栏ID：100002201

效果图：
![image](https://user-images.githubusercontent.com/7963197/216244734-cf93eae1-53e5-48fd-a7b4-f6a2243ac073.png)

错误日志：
time="2023-02-02T13:55:28+08:00" level=error msg="Request Timeout" func=github.com/nicoxiang/geektime-downloader/internal/pkg/logger.Error file="C:/Users/Administrator/go/pkg/mod/github.com/nicoxiang/geektime-downloader@v0.9.2/internal/pkg/logger/logger.go:58" error="context deadline exceeded"

**Comment by Camio1945** [comment]
关闭梯子又可以下载了。

**Comment by nicoxiang** [comment]
@Camio1945 ok，也感谢提供信息。经常有人提示会超时，情况各不相同，挺头疼的。

**Comment by Camio1945** [comment]
@nicoxiang 关闭梯子以后也确实还是会经常超时。不知道你的算法是怎样的，建议超时之后把时间窗口加倍后重试，再超时再加倍后重试，上限10分钟吧。或者给出超时重试次数的配置参数也行。
![image](https://user-images.githubusercontent.com/7963197/216258062-fbdfb890-52ac-418e-88dc-eb8327b95e0e.png)

**Comment by nicoxiang** [comment]
先靠重试吧，后面我再看下，其实我设的超时时间已经很长了，我自己试下来很少出现，我后面再看下

**Comment by Camio1945** [comment]
碰到一个超时概率为100%的专栏了。
专栏ID：100043001
专栏名称：摄影入门课
![image](https://user-images.githubusercontent.com/7963197/216896350-8b85920e-ab0a-4850-8f91-5100837af2da.png)

**Comment by nicoxiang** [comment]
@Camio1945 如果了解go的话可以像下面这样改下下面这一行源码重新build试试

https://github.com/nicoxiang/geektime-downloader/blob/main/internal/pdf/pdf.go#L181

networkIdle 改成 networkAlmostIdle

**Comment by nicoxiang** [comment]
[0.10.1-beta.1](https://github.com/nicoxiang/geektime-downloader/releases/tag/v0.10.1)
版本后增加--wait-seconds参数，现在Chrome生成PDF前的等待页面加载时间默认为8秒，可以通过该参数自行设置。

欢迎提交Issue/PR。
