### ISSUE TITLE
建议，关于视频下载

### ISSUE THREAD

**Issue by Shuimo03** [nicoxiang/geektime-downloader#92]
基本上专栏都可以下载，但是视频好像都是标清的，下载下来的视频有些会出现音画不同步现象。项目整体还是很好用的，感谢大佬开源

**Comment by nicoxiang** [comment]
视频清晰度可以设置参数，见文档： -q, --quality string   下载视频清晰度(ld标清,sd高清,hd超清) (default "sd")

音画不同步现象能否麻烦将有问题的课程名/号+章节名称+打包的视频文件发到我的邮箱，我后面看下是什么原因。邮箱 nicoxiang1@163.com

**Comment by cloud-arrow** [comment]
@nicoxiang 你好的专栏包含的视频无法下载吗？比如这个专栏 [https://time.geekbang.org/column/intro/100028301](https://time.geekbang.org/column/intro/100028301)
